services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rsrs88/nodejs-app:1.0
    ports:
      - "8080:80"
    volumes:
      - ./web/index.html:/app/web/index.html
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      placement:
        max_replicas_per_node: 10
